language: go
go:
- tip
script:
- make lint
- make test
after_script:
- make cover
before_deploy:
- make crossbuild
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RbRPnONqgpIS7vQ95L8fTdnCb94TiPUU9bUahLkhIvGJtxVRdc3zhK1Fb5vpbHlsQJRU3adpFlrZ5CS+vVydGaHzTohiw+vv+eeu8OKFF4sCEoRm7+5N7F8kpbr7bVNbEKzMVp5LhhDTHXlD/5H5YUkZHdmIEzhCZ9SyNx6HDzk0Y+dwqtJowXgqrxsoHho3ecjZ73T4S5BdATljxsYwqGpYKmOh1h+0orbgbALhniRjPuFfexmFiQqaAD4tCMs0ydow8a3aR76R/FzzKExPAM6umzso9d319hsQFQBDXUQYH0Xy2TgjZwJJN3FjZHCqV/OLYx+sWLGsx1OUHMuQ7i18vxeadObp3R8Qs4ZppnHubUgvu8/c8+zgq+fD8aQ7q7aOr3gEKhSbbyAYNQi9U0SLOxTpkglhCaMo4Vy3efpt8x0a1DBqQ/MUD5IzyvP7NHPuopvhM0tqs1DtA4JmHVb82a1b8fG96j6JX1zpQUfnexWO3CBs0TrE/mDAQ6qBoRdCdO0o4v7i5ZAcUPFJ/tWeopg0REOyD4z9StvYIUqWIfd80Ff+rblrCenN95No3WbNPON7F+ocpohJ3hVSxawsWiww3nbQmLu7bVTMZO8fzcTTEazRfVa5udRRU/f7Cu5evlX/gk+MbDxvJQhluIy1cndLIarUgVRk59bbAnI=
  file_glob: true
  file: "dist/**/*.{tar.gz,zip}"
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_TAG =~ ^v[0-9]+(?:\.[0-9]+){2}$"
