language: go
go:
- 1.16.x
script:
- make lint
- make test
after_script:
- make cover
before_deploy:
- make crossbuild
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DgyvCw9pgQULZnhG93//HClOw0J6CusWyZ0TDBz1g1yvmdloypYkd0Z0J4ff3IZnXam3lO1kC9yoaq9O6CM9FDNlFkoycAQwX5kGBI+AePgO2k9enJl7u7FUR2jV7MZT8cveooQqyLP3o8KdR2xqYFPw17yJv7j/ljDa1qu/8SC0M1O/WU2Lss91Wrv8JDzZx7MY65Gg9lMVjhiBW/sUrqh7nRY2yqSwO5zp+2vOxOyyy4ioVkEv3w0kakvIK9Cr2QDOok616WH0Rv3XC9rHQQXoucYCHq0jCXixSP/YDAIRJ3bMjLL1muZBu84dNTjlWryBJGjaz2MX62ikOJJwx4gcOc0l67hK6nyUTj0ZX6ns8fLNtRWjwb21r13snAWe17a6iru2TQ84sBKShEFP4w4xI2QmoDjgZJWnfw8k5Y0wz+F3wo6r8ne0DNR63R7x6Iwrf5l+ZhViwDFO01t0PGKf6cS30xpO47m1cqeHRGvro7bUNouMghUmBpzyAWEiPBiIHD6uxd4k4hvribcdGn4kho5nXOTGnYmLqK33yeFaiMKhfBh2LKZD/CguIE2wJkaArO/mTgr2Gh0D9wgY+MdKzAY/jI+4Cb5UJj5+IpUJmP32QR4VxTN0l3znKwDEFvGpzt0WdEPolG+ZKH5VonwYzfmbdmR3m/LLNd3kb5g=
  file_glob: true
  file: "dist/**/*.{tar.gz,zip}"
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
